typography_spectrum: 0.33206876111216843
color:
  brandStrength: 0.2685386224184185
  lightness: 0.5821498520672321
  saturation: 0.023127263179048896
  rhythmicContrast: 0.9608542930800468
  brandColors:
    - '#105B63'
    - '#FFFAD5'
    - '#FFD34E'
    - '#DB9E36'
    - '#BD4932'
layout_spectrum: 0.7082674875855446
analytics:
  google: UA-81716143-1
author:
  name: Jon Maldia
  email: jon@maldia.net
  url: ''
name: BoonSoh
navigation:
  - name: why boonsoh
    id: 0bb33a15-edb0-4aca-944f-f658a6acb4b8
    type: content
  - name: twitter
    url: 'http://www.twitter.com/jonmaldia'
    type: external
  - name: linkedin
    url: 'http://www.linkedin.com/in/jonmaldia'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bc34d1d7-50e0-44e2-8137-06c8de6ca3ab.ico
title: BoonSoh
description: A light-hearted way of helping you get through the day
