typography_spectrum: 0.32605684478767216
color:
  brandStrength: 0.8546292760875076
  lightness: 0.7847678025718778
  saturation: 0.44929469586350024
  rhythmicContrast: 0.7304378263652325
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
layout_spectrum: 0.3133394590113312
analytics:
  google: UA-81716143-1
author:
  name: Jon Maldia
  email: jon@maldia.net
  url: ''
name: BoonSoh
navigation:
  - name: why boonsoh
    id: 0bb33a15-edb0-4aca-944f-f658a6acb4b8
    type: content
  - name: twitter
    url: 'http://www.twitter.com/jonmaldia'
    type: external
  - name: linkedin
    url: 'http://www.linkedin.com/in/jonmaldia'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bc34d1d7-50e0-44e2-8137-06c8de6ca3ab.ico
title: BoonSoh
description: A light-hearted way of helping you get through the day
