typography_spectrum: 0.7155164133291692
color:
  brandStrength: 0.824126900639385
  lightness: 0.935094925109297
  saturation: 0.8833951475098729
  rhythmicContrast: 0.821042260620743
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
layout_spectrum: 0.3133394590113312
analytics:
  google: UA-81716143-1
author:
  name: Jon Maldia
  email: jon@maldia.net
  url: ''
name: BoonSoh
navigation:
  - name: why boonsoh
    id: 0bb33a15-edb0-4aca-944f-f658a6acb4b8
    type: content
  - name: twitter
    url: 'http://www.twitter.com/jonmaldia'
    type: external
  - name: linkedin
    url: 'http://www.linkedin.com/in/jonmaldia'
    type: external
favicon: null
title: BoonSoh
description: A light-hearted way of helping you get through the day
